[tool.poetry]
name = "stepflow"
version = "0.1.0"
description = ""
authors = ["Zhihao Liu <liuzhihao0206@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
alembic = "^1.15.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
